spring:
  application:
    name: empty-wallet

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
            model: claude-3-5-sonnet-20241022

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
              client-id: ${KAKAO_CLIENT_ID}
              client-secret: ${KAKAO_CLIENT_SECRET}
              client-authentication-method: client_secret_post
              redirect-uri: ${KAKAO_REDIRECT_URI}
              scope: ${KAKAO_SCOPE}
              authorization-grant-type: authorization_code
        provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

jwt:
  accessTokenExpirationMs: ${ACCESS_TOKEN_EXPIRATION_MS:3600000}
  refreshTokenExpirationMs: ${REFRESH_TOKEN_EXPIRATION_MS:86400000}
  secretKey: ${SECRET_KEY}

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  ssl:
    enabled: ${SSL_ENABLED}
    certificate: ${SSL_CERTIFICATE:dummy}
    certificate-private-key: ${SSL_SSL_CERTIFICATE_PRIVATE_KEY:dummy}
  port: ${SERVER_PORT}


springdoc:
  api-docs:
    version: OPENAPI_3_0
